### PR TITLE
Added Coke- blips on/off option -server police limit- added shop for more "hard" drugs

### PR DESCRIPTION
**Pull request by TheStonedRaider**

### CODE REVIEW

**Comment by grantfoster** [comment]
<3 the coke is gonna help me do all the ones i want by having two examples to start from.
thanks much

**Comment by BackrndSource** [comment]
Coke plants are flying!

**Comment by ElPumpo** [comment]
It's the exact same code as weed, and has 50000 commits?

**Comment by TheStonedRaider** [comment]
Yea well sorry for it being one of the first scripts that I've ever done but I got it correct in the end. if you are guna be rude then don't expect any help in the future.

**Comment by littl3ird** [comment]
@TheStonedRaider  
Hi , I am noob and clearly dont know anything  . I follow every step as you did. But when I come to coke field , its nothing there , I cant see any access to pick up coke . if you need anything please tell me . Thank you so much !

**Pull request closed without merging**
